name: WasteSify
description: WasteSify is a A.I Based Mobile Application that classify Biodegradable/Non-biodegradable waste in realtime.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.5.7+4
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  percent_indicator: ^2.1.1+1
  
 

  tflite: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.2
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/model.tflite
    - assets/labels.txt
    - assets/logo/logo.png
    - assets/logo/bg.jpg
    - assets/icon/header.png
    - assets/icon/cameraheader.png
    
